name: Lint C#

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Restore dependencies
        run: dotnet restore src/MyApp.csproj

      - name: Check code formatting
        run: dotnet format --verify-no-changes src/MyApp.csproj
