name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore DevOps-Formativas.sln
      - run: dotnet build DevOps-Formativas.sln --configuration Debug --no-restore
      - run: dotnet test DevOps-Formativas.sln --configuration Debug --no-build --logger "trx;LogFileName=test-results.trx" --results-directory TestResults
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-results
          path: TestResults/**/*.trx
