name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore DevOps-Formativas.sln

      - name: Build (Debug)
        run: dotnet build DevOps-Formativas.sln --configuration Debug --no-restore

      - name: Run tests (emit TRX)
        run: dotnet test DevOps-Formativas.sln --configuration Debug --no-build --logger "trx;LogFileName=tests.trx" --results-directory TestResults

      - name: List TRX files (debug)
        if: always()
        run: ls -lR TestResults || true

      - name: Publish test report (Checks)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Tests (Debug)
          path: TestResults/**/*.trx
          reporter: dotnet-trx
          fail-on-error: false
          fail-on-empty: false

      - name: Upload TRX artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-results
          path: TestResults/**/*.trx
