name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet restore DevOps-Formativas.sln
      - run: dotnet build DevOps-Formativas.sln --configuration Debug --no-restore
      - name: Run tests (emit TRX)
        run: dotnet test WebApi.Tests/WebApi.Tests.csproj --configuration Debug --no-build --logger "trx;LogFileName=WebApi.Tests.trx" --results-directory WebApi.Tests/TestResults
      - name: List results (debug)
        if: always()
        run: ls -R WebApi.Tests/TestResults || true
      - name: Publish test report (Checks)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Tests (Debug)
          path: WebApi.Tests/TestResults/**/*.trx
          reporter: dotnet-trx
          fail-on-error: false
      - name: Upload TRX artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-results
          path: WebApi.Tests/TestResults/**/*.trx
