name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/WebApi.csproj

      - name: Build
        run: dotnet build src/WebApi.csproj --configuration Release

      - name: Test (with results file)
        run: dotnet test src/WebApi.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: List test results
        run: |
          if (Test-Path "src\TestResults\") { dir src\TestResults\ } else { echo "No test results folder found." }

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: src/TestResults/**/*.trx

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: src/bin/Release/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deliver
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
      - name: Display structure of downloaded files
        run: ls -R
