name: Lint C#

on: [push, pull_request]

jobs:
  build-and-deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Restore dependencies
        run: dotnet restore src/WebApi.csproj

      - name: Check code formatting
        run: dotnet format --verify-no-changes src/WebApi.csproj

  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  discord-webhook:
    if: ${{ github.event_name == 'push' && github.event.head_commit != null }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
