name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-deliver:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore src/MyApp.csproj

      - name: Build
        run: dotnet build src/MyApp.csproj --configuration Release

      - name: Test (with results file)
        run: dotnet test src/MyApp.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: src/bin/Release/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: src/TestResults/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deliver
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: List downloaded files
        run: ls -R

      - name: List test results
        run: dir src\TestResults\
