name: Lint C# + Docker

on: [push, pull_request]

jobs:
  build-and-deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Restore dependencies (app)
        run: dotnet restore src/WebApi.csproj

      - name: Restore dependencies (tests)
        run: dotnet restore tests/WebApi.Tests/WebApi.Tests.csproj

      - name: Check code formatting
        run: dotnet format --verify-no-changes src/WebApi.csproj

      - name: Run unit tests
        run: dotnet test tests/WebApi.Tests/WebApi.Tests.csproj --configuration Debug --logger "trx;LogFileName=test-results.trx" --results-directory tests/WebApi.Tests/TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-results
          path: tests/WebApi.Tests/TestResults/**/*.trx

  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3